node_js:
- "7"
- "8"
- "9"
sudo: false
language: node_js
script: "npm run test"
# after_success: "npm i -g codecov && npm run coverage && codecov"
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
